# Generated by Django 3.2.19 on 2023-06-16 15:42

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YogaExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('level', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('yoga_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.yogaday')),
            ],
        ),
        migrations.CreateModel(
            name='YogaPoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YogaWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yoga_exercises', models.ManyToManyField(to='yoga.YogaExercise')),
            ],
        ),
        migrations.AddField(
            model_name='yogaexercise',
            name='yoga_poses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.yogaposes'),
        ),
        migrations.AddField(
            model_name='yogaday',
            name='yoga_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.yogaexercise'),
        ),
    ]
