# Generated by Django 3.2.19 on 2023-06-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaexercise',
            name='yoga_day',
        ),
    ]
