# Generated by Django 3.2.19 on 2023-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_auto_20230616_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaexercise',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
