# Generated by Django 3.2.19 on 2023-06-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_yogaexercise_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YogaDay',
        ),
    ]
