# Generated by Django 3.2.19 on 2023-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_onlinebooking_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='table',
            field=models.CharField(choices=[('Family table', 'Family table'), ('Outdoor seating', 'Outdoor seating'), ('Table for two', 'Table for two'), ('Table on second floor (sea view)', 'Table on second floor (sea view)')], default='Family table', max_length=150),
        ),
    ]
