# Generated by Django 3.2.19 on 2023-06-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_contactdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='online_booking',
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='contact_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_booking', to='reservation.contactdetails'),
            preserve_default=False,
        ),
    ]
