# Generated by Django 3.2.19 on 2023-06-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20230628_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebooking',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='online_booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_booking', to='reservation.onlinebooking'),
            preserve_default=False,
        ),
    ]
